apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
data:
  KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-service:9092
  KAFKA_LISTENERS: PLAINTEXT://:9092
  KAFKA_ZOOKEEPER_CONNECT: localhost:2181